name: lol-repository

services:
  postgres:
    image: postgres:18-alpine
    container_name: lol-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgresCLAUDE
    volumes:
      - ./postgres-data:/var/lib/postgresql
  # 2. 통계를 처리할 분석 DB (ClickHouse)
  clickhouse_analytics:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_analytics
    ports:
      - "8123:8123" # HTTP 인터페이스
      - "9000:9000" # 기본 클라이언트 포트
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: lol-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: lol-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
