services:
  postgres:
    image: postgres:18-alpine
    container_name: lol-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgresCLAUDE
    volumes:
      - ./postgres-data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: lol-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: lol-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
